# Generated by Django 2.1.3 on 2019-01-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190117_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pet',
        ),
    ]
