# Generated by Django 2.1.3 on 2019-01-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20181123_1645'),
        ('contacts', '0003_remove_contact_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pettt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pets.Pet'),
            preserve_default=False,
        ),
    ]
