# Generated by Django 2.1.3 on 2019-01-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_pettt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pettt',
            new_name='pet',
        ),
    ]
